---
title: "IPL 2020 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: paper
    logo: ./images/ipl-logo.jpg
    source_code: embed
    social: ["twitter"]
runtime: shiny
---

```{r setup, include=FALSE}
suppressMessages(library('flexdashboard', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('ggplot2', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('tidyverse', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('rnaturalearth', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('sp', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('leaflet', warn.conflict = FALSE, quietly = TRUE))
suppressMessages(library('plotly', warn.conflict = FALSE, quietly = TRUE))
```

```{r}
# IPL 2020 squads
data <- read_csv("data/Squads_IPL_2020.csv")
matches <- read_csv("data/Matches_IPL_2020.csv")
```

Home {data-icon="fa-table"}
=======================================================================

Row
-----------------------------------------------------------------------

### Total Teams

```{r}
# Total number of countries representing in IPL
teams <- data %>% count(Player_ipl_team) %>% count()
valueBox(teams, icon="fas fa-users")
```

### Total Countries

```{r}
# Total number of countries representing in IPL
countries <- data %>% count(Player_country) %>% count()
valueBox(countries, icon="fa-globe")
```

### Total Indian Players 

```{r}
# Total number of countries representing in IPL
indian_players <- data %>% filter(Player_country == "India") %>% count()
valueBox(indian_players, icon="fa-rupee-sign")
```

### Total Players

```{r}
# Total number of players representing in IPL
players <- data %>% count()
valueBox(players, icon="fas fa-running")
```

### Total Matches

```{r}
# Total number of players representing in IPL
total_matches <- matches %>% count()
valueBox(total_matches, icon="fa-border-all")
```

### Total prize money

```{r}
# Total number of players representing in IPL
valueBox("2.8M", icon="fas fa-dollar-sign")
```

Row
-----------------------------------------------------------------------

### Countries representing in IPL:

```{r}
map <- ne_countries()
names(map)[names(map) == "iso_a3"] <- "ISO3"
names(map)[names(map) == "name"] <- "NAME"

countries <- data %>% count(Player_country) %>% pull(Player_country)
values <- data %>% count(Player_country) %>% pull(n)

d <- data.frame("iso3c" = c("AFG", "AUS", "GBR", "IND", "NPL", "NZL", "ZAF", "LKA", "JAM"), NAME = countries, value = values)
map$players <- d[match(map$ISO3, d$iso3c), "value"]

pal <- colorBin(
  palette = "viridis", domain = map$players,
  bins = seq(0, max(map$players, na.rm = TRUE) + 10, by = 25)
)

map$labels <- paste0(
  "<strong> Country: </strong> ",
  map$NAME, "<br/> ",
  "<strong> players: </strong> ",
  map$players, "<br/> "
) %>%
  lapply(htmltools::HTML)

leaflet(map) %>%
  addTiles() %>%
  setView(lng = 50, lat = 30, zoom = 2) %>%
  addPolygons(
    fillColor = ~ pal(players),
    color = "white",
    fillOpacity = 0.7,
    label = ~labels,
    highlight = highlightOptions(
      color = "black",
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~players,
    opacity = 0.7, title = "Players"
  )
```

IPL squad {data-icon="fas fa-users"}
=======================================================================

Row {data-height=650}
-------------------------------------

### IPL Squad

```{r, fig.width=20}
squads <- read_csv("data/Squads_IPL_2020.csv")
country_team <- squads %>% count(Player_country, Player_ipl_team, sort = TRUE) %>% 
  mutate(Player_country = fct_reorder(Player_country, n))
p <- ggplot(country_team, aes(Player_country, n, fill = Player_country)) + geom_col() + 
  theme_light() + labs(y = "", x = "") + theme(legend.position = "none") + facet_grid(~Player_ipl_team, scales = "free", space = "free") + theme(axis.text.x = element_text(size = 12, angle=45, hjust = 1, vjust = 1), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 13))
ggplotly(p)
```

Row {data-height=550}
-------------------------------------
   
### Total number of players per IPL team

```{r, fig.width=8}
squads %>% count(Player_ipl_team, sort = TRUE) %>% mutate(Player_ipl_team = fct_reorder(Player_ipl_team, n)) %>% ggplot(aes(n, Player_ipl_team, fill = Player_ipl_team)) + geom_col() + theme_light() + labs(x = "Number of Players", y = "IPL team") + theme(legend.position = "") + theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16))
```   
    
### Total number of players per Country

```{r, fig.width=8}
squads %>% count(Player_country, sort = TRUE) %>% mutate(Player_country = fct_reorder(Player_country, n)) %>% ggplot(aes(n, Player_country, fill = Player_country)) + geom_col() + theme_light() + labs(x = "Number of Players", y = "Country") + theme(legend.position = "") + theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16))
```

IPL stats {data-icon="ion-stats-bars"}
=======================================================================

Row {data-height=550}
-------------------------------------

### Top 5 batsman per team

```{r}
deliveries <- read_csv("data/Deliveries_IPL_2020.csv")

shinyApp(
  ui = fillPage(
    fillCol(flex = c(NA, 1),
      inputPanel(
        selectInput("team", "IPL Team:", choices = unique(deliveries$batting_team), selected = "MI", selectize=TRUE)
      ),
      plotlyOutput("readPlot", height = "100%")
    )
  ),
  server = function(input, output) {
    output$readPlot <- renderPlotly({
            top5 <- deliveries %>% filter(batting_team == input$team) %>% group_by(batsman) %>% summarize(n()) %>% arrange(desc(`n()`)) %>% head(5) %>% rename(runs = 2) %>%  mutate(batsman = fct_reorder(batsman, runs))
            p <- ggplot(top5, aes(runs, batsman, fill = batsman)) +
              geom_col(position = "dodge") +  theme_minimal() + labs(y = "", x = "Runs") + theme(legend.position = "none") +
              theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12))
            ggplotly(p)
    })
  },
  options = list(height = 500)
)
```

### Top 5 bowlers per IPL Team

```{r}
shinyApp(
  ui = fillPage(
    fillCol(flex = c(NA, 1),
      inputPanel(
        selectInput("team", "IPL Team:", choices = unique(deliveries$bowling_team), selected = "MI", selectize=TRUE)
      ),
      plotlyOutput("readPlot", height = "100%")
    )
  ),
  server = function(input, output) {
    output$readPlot <- renderPlotly({
            top5 <- deliveries %>% filter(!is.na(player_dismissed)) %>% group_by(bowling_team, bowler) %>% summarize(n()) %>% arrange(desc(`n()`)) %>% filter(bowling_team == input$team) %>% head(5) %>% rename(wickets = 3) %>%  mutate(bowler = fct_reorder(bowler, wickets))
            p <- ggplot(top5, aes(wickets, bowler, fill = bowler)) +
              geom_col(position = "dodge") +  theme_minimal() + labs(y = "", x = "Wickets") + theme(legend.position = "none") +
              theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12))
            ggplotly(p)
    })
  },
  options = list(height = 500)
)
```

### Chart 3

```{r}

```

Row {data-height=550}
-------------------------------------
   
### Chart 4

```{r}
```   
    
### Chart 5

```{r}
```

### Chart 6

```{r}

```
